# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fatih.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(761, 729)
        Form.setStyleSheet("*{color:rgb(17, 60, 79); font-family:Times New Roman}\n"
"QToolButton{\n"
"background-color:rgb(17, 60, 79);\n"
"border-radius:10px;\n"
"}\n"
"QFrame{background-color:rgb(104, 104, 104);}\n"
"QPushButton{\n"
"background-color:red;\n"
"border-radius:4px;\n"
"}\n"
"QLabel{\n"
"text-align: rightr;\n"
"}\n"
"QLineEdit{\n"
"background-color: Grey;\n"
"border-radius:1px;\n"
"border-color:Grey;\n"
"font-size:14px;\n"
"font-family:Poppins;\n"
"}")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(180, 160, 401, 421))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 50, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(130, 340, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(70, 129, 261, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 180, 261, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(340, 100, 81, 81))
        self.toolButton.setStyleSheet("image: url(:/fatih/ghost.png);")
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Login Here"))
        self.pushButton.setText(_translate("Form", "Giriş"))
        self.lineEdit.setText(_translate("Form", "Username"))
        self.lineEdit_2.setText(_translate("Form", "Password"))
        self.toolButton.setText(_translate("Form", "..."))
import ghost_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
